version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: lecture_db
    ports:
      - "3306:3306"
    volumes:
      - ../lecture_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'lecture2024'
      MYSQL_DATABASE: lecture_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
