INSERT INTO student (id, name)
VALUES (1, 'John Doe'),
       (2, 'Jane Smith'),
       (3, 'Michael Johnson'),
       (4, 'Emily Davis'),
       (5, 'James Brown'),
       (6, 'Mary Wilson'),
       (7, 'David Lee'),
       (8, 'Sarah Taylor'),
       (9, 'William Anderson'),
       (10, 'Jessica Thomas'),
       (11, 'Joshua Martinez'),
       (12, 'Laura Harris'),
       (13, 'Andrew Clark'),
       (14, 'Olivia Lewis'),
       (15, 'Daniel Walker'),
       (16, 'Sophia Hall'),
       (17, 'Matthew Allen'),
       (18, 'Avery Young'),
       (19, 'Lucas King'),
       (20, 'Grace Scott');
